# Generated by Django 5.1.6 on 2025-03-15 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['video_order']},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='access_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Restricted', 'Restricted')], default='Restricted', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='James', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_duration',
            field=models.DurationField(default='00:00:00', editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_videos',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='courseregistration',
            index=models.Index(fields=['user', 'course'], name='courses_cou_user_id_d1d49c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'video'], name='courses_use_user_id_69030b_idx'),
        ),
    ]
