# Generated by Django 5.1.6 on 2025-03-15 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_display_name_video_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='watched_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
